version: '3'

services:
  postgresdb:
    build: ./docker/postgres/.
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_db
    volumes:
    - posgresdb-data:/var/lib/postgresql/data
    ports:
    - 6432:5432
  dataloader:
    build: ./docker/data_loader/.
    container_name: etl_pipeline
    volumes:
    - ./src/data_loader/:/app/src/data_loader/
    - ./data/:/app/data/
  api:
    build: ./docker/api/.
    container_name: voucher_api
    volumes:
    - ./src/api/:/app/api/
    ports:
      - "8000:8000"
    depends_on:
      - postgresdb
volumes:
  posgresdb-data:
    driver: local